FROM python:3.8-slim
ENV PYTHONUNBUFFERED 1
WORKDIR /workspace

RUN apt-get update && apt-get install -y wget gnupg

COPY requirements.txt /workspace/
COPY ./ /workspace/
RUN pip install -r requirements.txt

RUN useradd -m recoani
USER recoani

CMD ["python", "./src/test.py"]
